### PR TITLE
Pull Development into main

### PR DESCRIPTION
**Pull request by SverreNystad**

### CODE REVIEW

**Comment by SverreNystad** [comment]
The hope is that the backend will be automatically deployed on merge with main

**Review by sandviklee — APPROVED** [review]
Can't wait to see if this works:) Great work!

**Comment by sandviklee** [comment]
Woopsie, a bit fast in the fingers there. Almost deleted the dev branch lol

**Comment by SverreNystad** [comment]
xD

**Comment by SverreNystad** [comment]
Have almost done that 3 times

**Comment by sandviklee** [comment]
Haha, classic

**Comment by SverreNystad** [comment]
Need to change the Personal Access token for it to work

**Pull request merged**
