### PR TITLE
feat: add endpoint to update image of members by sending a list of Images with correct names

### PR DESCRIPTION
**Pull request by SverreNystad**
### How to test:
Use this command in the terminal:

```bash
curl -X POST -F "images=@path_to_image.jpg" http://localhost:8000/api/member/image
```

Go to the swagger upload some images with names of Members and non members and check the Members afterwards

### CODE REVIEW

**Review by sandviklee — CHANGES_REQUESTED** [review]
Just to be sure, are there any permission checking on this endpoint? Couldn't see if there were any. We don't want any randoms changing our images hehe... Otherwise it looks good! Great work 😄

**Comment by SverreNystad** [comment]
> Just to be sure, are there any permission checking on this endpoint? Couldn't see if there were any. We don't want any randoms changing our images hehe... Otherwise it looks good! Great work 😄

Oh I thought I added it must check. One sec

**Comment by SverreNystad** [comment]
> > Just to be sure, are there any permission checking on this endpoint? Couldn't see if there were any. We don't want any randoms changing our images hehe... Otherwise it looks good! Great work 😄
> 
> Oh I thought I added it must check. One sec

Authentication is now added

**Review by sandviklee — APPROVED** [review]
Great! LGTMIHRTC! 🚀

**Comment by SverreNystad** [comment]
Now we also have tests for only authenticated users can make requests and non authorized gets HTTP_403_FORBIDDEN

**Comment by SverreNystad** [comment]
@sandviklee  Good spot with the permissions!

**Pull request merged**
